:: assign filename variable based on today's date 
set vDate=%date:~-4%%date:~4,2%%date:~7,2%
set vFileName=J:\NM BSA\NPM_Facets\PROD\scorecard_%vDate%

:: check if current date scorecard file exists. 
:: if not send notification email.  otherwise run batch.
if not exist "%vFileName%*.zip" (
	"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -CONFIG "C:\Program Files\SASHome\SASFoundation\9.4\nls\en\sasv9.cfg" -AUTOEXEC "H:\AUTOEXEC.SAS" -SYSIN "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F00-Facets_Scorecard_Missing.sas" -LOG  "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F00-Facets_Scorecard_Missing.log"
	exit
	) else (
	goto labelExists
	)
	
:labelExists
:: pull data.. save locally
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0stage -s "|" -W -Q "set nocount on; SELECT COALESCE (NPI,'') NPI, COALESCE (NPI_TYPE_I,'') NPI_TYPE_I, COALESCE (NPI_TYPE_II,'') NPI_TYPE_II, COALESCE (NPI_KEY,'') NPI_KEY, COALESCE (PROV_ID,'') PROV_ID, COALESCE (DEA_NO,'') DEA_NO, COALESCE (TAX_ID,'') TAX_ID, COALESCE (PROV_TYPE,'') PROV_TYPE, COALESCE (PRIM_SPEC,'') PRIM_SPEC, COALESCE (CUSTOM_VAL2,'') CUSTOM_VAL2, COALESCE (TCAT_VALUE,'') TCAT_VALUE, COALESCE (PRPR_ENTITY,'') PRPR_ENTITY, COALESCE (RLET_ID,'') RLET_ID, COALESCE (PRCP_ID,'') PRCP_ID, COALESCE (PRPR_ID,'') PRPR_ID, COALESCE (ENTITY_ID,'') ENTITY_ID, COALESCE (PRPR_KEYFIELD,'') PRPR_KEYFIELD, COALESCE (PRPR_ID_IN_FACETS,'') PRPR_ID_IN_FACETS, COALESCE (PRCP_ID_IN_FACETS,'') PRCP_ID_IN_FACETS, COALESCE (ADDR_SHARING,'') ADDR_SHARING FROM dbo.tpzt_apm_fac_xwlk" -o "C:\facets\tpzt_apm_fac_xwlk.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; SELECT COALESCE(MCBR_CK,'') MCBR_CK,COALESCE(MCBR_REL_TYPE,'') MCBR_REL_TYPE,COALESCE(MCBR_REL_CK,'') MCBR_REL_CK,COALESCE(MCBR_REL_ID,'') MCBR_REL_ID,COALESCE(MCBD_ID,'') MCBD_ID,COALESCE(MCBR_ACCT_NO,'') MCBR_ACCT_NO,COALESCE(MCBR_ACCT_NAME,'') MCBR_ACCT_NAME,COALESCE(MCBR_MCTR_ATYP,'') MCBR_MCTR_ATYP,COALESCE(MCBR_ACCT_NO_QUAL,'') MCBR_ACCT_NO_QUAL,COALESCE(MCBR_LOCK_TOKEN,'') MCBR_LOCK_TOKEN,COALESCE(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID FROM dbo.CMC_MCBR_BANK_REL" -o "C:\facets\CMC_MCBR_BANK_REL.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; SELECT COALESCE(MCTI_ENTY_ID,'')  MCTI_ENTY_ID, COALESCE(MCTI_TYPE,'')  MCTI_TYPE, COALESCE(MCTI_EFF_DT,'')  MCTI_EFF_DT, COALESCE(MCTI_TERM_DT,'')  MCTI_TERM_DT, COALESCE(MCTI_MCTR_TRSN,'')  MCTI_MCTR_TRSN, COALESCE(MCTN_ID,'')  MCTN_ID, COALESCE(MCTN_TYPE,'')  MCTN_TYPE, COALESCE(MCTI_LOCK_TOKEN,'') MCTI_LOCK_TOKEN, COALESCE(ATXR_SOURCE_ID,'')  ATXR_SOURCE_ID  from dbo.CMC_MCTI_TAX_INFO" -o "C:\facets\CMC_MCTI_TAX_INFO.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on;  Select COALESCE ( a.PRPR_ID,'') PRPR_ID,COALESCE ( a.PRPR_ENTITY,'') PRPR_ENTITY,COALESCE ( a.PRPR_NAME,'') PRPR_NAME,COALESCE ( a.PRPR_CL_EFT_IND,'') PRPR_CL_EFT_IND,COALESCE ( b.PRAD_TYPE,'') PRAD_TYPE,COALESCE ( b.PRAD_ADDR1,'') PRAD_ADDR1,COALESCE ( b.PRAD_ADDR2,'') PRAD_ADDR2,COALESCE ( b.PRAD_CITY,'') PRAD_CITY,COALESCE ( b.PRAD_STATE,'') PRAD_STATE,COALESCE ( b.PRAD_ZIP,'') PRAD_ZIP,COALESCE ( b.PRAD_EFF_DT,'') PRAD_EFF_DT,COALESCE ( b.PRAD_TERM_DT,'') PRAD_TERM_DT,COALESCE ( c.MCBD_ID,'') MCBD_ID,COALESCE ( c.MCBR_ACCT_NAME,'') MCBR_ACCT_NAME,COALESCE ( c.MCBR_ACCT_NO,'') MCBR_ACCT_NO,COALESCE ( c.MCBR_CK,'') MCBR_CK from CMC_PRPR_PROV a inner join CMC_PRAD_ADDRESS b on a.PRPR_ID = b.PRAD_ID left join CMC_MCBR_BANK_REL c on a.MCBR_CK = c.MCBR_CK where b.PRAD_TYPE = 'RMT' and b.PRAD_TERM_DT = '9999-12-31 00:00:00.000' and a.PRPR_ENTITY <> 'P' and LEN(a.PRPR_ID) = '8' order by a.PRPR_ID" -o "C:\facets\ACCT_REMIT.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PRPR_ID,'') PRPR_ID, coalesce(PRDS_EFF_DT,'') PRDS_EFF_DT , coalesce(PRDS_TERM_DT,'') PRDS_TERM_DT , coalesce(PRDS_MCTR_TRSN,'') PRDS_MCTR_TRSN , coalesce(PRDS_PAY_CL_IND,'') PRDS_PAY_CL_IND , coalesce(PRDS_PAY_CAP_IND,'') PRDS_PAY_CAP_IND , coalesce(PRDS_LOCK_TOKEN,'') PRDS_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID from dbo.CMC_PRDS_DATE" -o "C:\facets\CMC_PRDS_DATE.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(MCTN_ID,'') MCTN_ID, coalesce(MCTN_TYPE,'') MCTN_TYPE, coalesce(MCTN_NAME,'') MCTN_NAME, coalesce(MCTN_LST_NAME,'') MCTN_LST_NAME, coalesce(MCTN_FIRST_NAME,'') MCTN_FIRST_NAME, coalesce(MCTN_MID_INIT,'') MCTN_MID_INIT, coalesce(MCTN_TITLE,'') MCTN_TITLE, coalesce(MCTN_STATUS,'') MCTN_STATUS, coalesce(MCTN_ADDR1,'') MCTN_ADDR1, coalesce(MCTN_ADDR2,'') MCTN_ADDR2, coalesce(MCTN_ADDR3,'') MCTN_ADDR3, coalesce(MCTN_CITY,'') MCTN_CITY, coalesce(MCTN_STATE,'') MCTN_STATE, coalesce(MCTN_ZIP,'') MCTN_ZIP, coalesce(MCTN_COUNTY,'') MCTN_COUNTY, coalesce(MCTN_CTRY_CD,'') MCTN_CTRY_CD, coalesce(MCTN_PHONE,'') MCTN_PHONE, coalesce(MCTN_PHONE_EXT,'') MCTN_PHONE_EXT, coalesce(MCTN_FAX,'') MCTN_FAX, coalesce(MCTN_FAX_EXT,'') MCTN_FAX_EXT, coalesce(MCTN_EMAIL,'') MCTN_EMAIL, coalesce(MCTN_LOCK_TOKEN,'') MCTN_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID from dbo.CMC_MCTN_TAX_NAME" -o "C:\facets\CMC_MCTN_TAX_NAME.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(MCTR_ENTITY,'') MCTR_ENTITY, coalesce(MCTR_TYPE,'') MCTR_TYPE, coalesce(MCTR_VALUE,'') MCTR_VALUE, coalesce(MCTR_DESC,'') MCTR_DESC, coalesce(MCTR_FILTER,'') MCTR_FILTER, coalesce(MCTR_VALUE_SIZE,'') MCTR_VALUE_SIZE, coalesce(MCTR_SORT,'') MCTR_SORT, coalesce(MCTR_LOCK_TOKEN,'') MCTR_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID, coalesce(SYS_LAST_UPD_DTM,'') SYS_LAST_UPD_DTM, coalesce(SYS_USUS_ID,'') SYS_USUS_ID, coalesce(SYS_DBUSER_ID,'') SYS_DBUSER_ID from dbo.CMC_MCTR_CD_TRANS" -o "C:\facets\CMC_MCTR_CD_TRANS.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PRPR_ID,'') PRPR_ID, coalesce(PRPR_ENTITY,'') PRPR_ENTITY, coalesce(PRCR_ID,'') PRCR_ID, coalesce(TPCT_MCTR_TCAT,'') TPCT_MCTR_TCAT, coalesce(PRPR_PAY_CL_METH,'') PRPR_PAY_CL_METH, coalesce(PRPR_MCTR_TYPE,'') PRPR_MCTR_TYPE, coalesce(PRPR_MCTR_PRTY,'') PRPR_MCTR_PRTY, coalesce(PRCF_MCTR_SPEC,'') PRCF_MCTR_SPEC, coalesce(PRPR_NAME,'') PRPR_NAME, coalesce(PRPR_NPI,'') PRPR_NPI, coalesce(PRCP_ID,'') PRCP_ID, coalesce(PRAD_ID,'') PRAD_ID, coalesce(PRAD_TYPE_CHECK,'') PRAD_TYPE_CHECK, coalesce(PRAD_TYPE_PRIM,'') PRAD_TYPE_PRIM, coalesce(MCTN_ID,'') MCTN_ID, coalesce(PRPR_STS,'') PRPR_STS, coalesce(PRPR_MCTR_REV,'') PRPR_MCTR_REV, coalesce(PRPR_PREAUTH_IND,'') PRPR_PREAUTH_IND, coalesce(PRPR_PAY_HOLD_DT,'') PRPR_PAY_HOLD_DT, coalesce(PRPR_OPTS,'') PRPR_OPTS, coalesce(PRPR_CL_EFT_IND,'') PRPR_CL_EFT_IND, coalesce(PRPR_CAP_EFT_IND,'') PRPR_CAP_EFT_IND, coalesce(PRPR_NAME_XLOW,'') PRPR_NAME_XLOW, coalesce(PRPR_LAST_CHAN_DTM,'') PRPR_LAST_CHAN_DTM, coalesce(PRPR_MCTR_LANG,'') PRPR_MCTR_LANG, coalesce(PRPR_EXTN_ADDR_IND,'') PRPR_EXTN_ADDR_IND, coalesce(MCBR_CK,'') MCBR_CK, coalesce(USUS_ID,'') USUS_ID, coalesce(CRCY_ID,'') CRCY_ID, coalesce(PRPR_TERM_DT,'') PRPR_TERM_DT, coalesce(PRPR_MCTR_TRSN,'') PRPR_MCTR_TRSN, coalesce(PRPR_TAXONOMY_CD,'') PRPR_TAXONOMY_CD, coalesce(PRPR_EDI_DEST_ID,'') PRPR_EDI_DEST_ID, coalesce(PRPR_EDI_DEST_QUAL,'') PRPR_EDI_DEST_QUAL, coalesce(PRPR_RA_DEST_IND,'') PRPR_RA_DEST_IND, coalesce(PRPR_CLRNGHOUSE_ID,'') PRPR_CLRNGHOUSE_ID, coalesce(PRPR_LAST_MCPA_DTM,'') PRPR_LAST_MCPA_DTM, coalesce(PRPR_PR_RED_CD,'') PRPR_PR_RED_CD, coalesce(PRCF_MCTR_SPEC2,'') PRCF_MCTR_SPEC2, coalesce(PRPR_MCTR_VAL1,'') PRPR_MCTR_VAL1, coalesce(PRPR_MCTR_VAL2,'') PRPR_MCTR_VAL2, coalesce(PRPR_RMT_TRANS_CD,'') PRPR_RMT_TRANS_CD, coalesce(PRPR_RMT_DEL_NAME,'') PRPR_RMT_DEL_NAME, coalesce(PRPR_RMT_COMM_NO,'') PRPR_RMT_COMM_NO, coalesce(PRPR_LOCK_TOKEN,'') PRPR_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID, coalesce(SYS_LAST_UPD_DTM,'') SYS_LAST_UPD_DTM, coalesce(SYS_USUS_ID,'') SYS_USUS_ID, coalesce(SYS_DBUSER_ID,'') SYS_DBUSER_ID, coalesce(PRPR_PA_RA_END_DT_NVL,'') PRPR_PA_RA_END_DT_NVL from dbo.CMC_PRPR_PROV" -o "C:\facets\CMC_PRPR_PROV.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PRPR_ID,'') PRPR_ID, coalesce(PRER_PRPR_ENTITY,'') PRER_PRPR_ENTITY, coalesce(PRER_EFF_DT,'') PRER_EFF_DT, coalesce(PRER_TERM_DT,'') PRER_TERM_DT, coalesce(PRER_MCTR_TRSN,'') PRER_MCTR_TRSN, coalesce(PRER_PRPR_ID,'') PRER_PRPR_ID, coalesce(MCRV_REL_VALUE_CD,'') MCRV_REL_VALUE_CD, coalesce(PRER_REL_VAL_IND,'') PRER_REL_VAL_IND, coalesce(PRER_LOCK_TOKEN,'') PRER_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID, coalesce(SYS_LAST_UPD_DTM,'') SYS_LAST_UPD_DTM, coalesce(SYS_USUS_ID,'') SYS_USUS_ID, coalesce(SYS_DBUSER_ID,'') SYS_DBUSER_ID from dbo.CMC_PRER_RELATION" -o "C:\facets\CMC_PRER_RELATION.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PRAD_ID,'') PRAD_ID, coalesce(PRAD_TYPE,'') PRAD_TYPE, coalesce(PRAD_EFF_DT,'') PRAD_EFF_DT, coalesce(PRAD_TERM_DT,'') PRAD_TERM_DT, coalesce(PRAD_ADDR1,'') PRAD_ADDR1, coalesce(PRAD_ADDR2,'') PRAD_ADDR2, coalesce(PRAD_ADDR3,'') PRAD_ADDR3, coalesce(PRAD_CITY,'') PRAD_CITY, coalesce(PRAD_STATE,'') PRAD_STATE, coalesce(PRAD_ZIP,'') PRAD_ZIP, coalesce(PRAD_COUNTY,'') PRAD_COUNTY, coalesce(PRAD_CTRY_CD,'') PRAD_CTRY_CD, coalesce(PRAD_PHONE,'') PRAD_PHONE, coalesce(PRAD_PHONE_EXT,'') PRAD_PHONE_EXT, coalesce(PRAD_FAX,'') PRAD_FAX, coalesce(PRAD_FAX_EXT,'') PRAD_FAX_EXT, coalesce(PRAD_EMAIL,'') PRAD_EMAIL, coalesce(PRAD_HD_IND,'') PRAD_HD_IND, coalesce(PRAD_PRACTICE_IND,'') PRAD_PRACTICE_IND, coalesce(PRAD_CITY_XLOW,'') PRAD_CITY_XLOW, coalesce(PRAD_TYPE_MAIL,'') PRAD_TYPE_MAIL, coalesce(PRAD_MCTR_TRSN,'') PRAD_MCTR_TRSN, coalesce(PRAD_DIRECTORY_IND,'') PRAD_DIRECTORY_IND, coalesce(PRAD_LONG,'') PRAD_LONG, coalesce(PRAD_LAT,'') PRAD_LAT, coalesce(PRAD_GEO_RTRN_CD,'') PRAD_GEO_RTRN_CD, coalesce(PRAD_LOCK_TOKEN,'') PRAD_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID, coalesce(SYS_LAST_UPD_DTM,'') SYS_LAST_UPD_DTM, coalesce(SYS_USUS_ID,'') SYS_USUS_ID, coalesce(SYS_DBUSER_ID,'') SYS_DBUSER_ID, coalesce(PRAD_MEL_RTRN_CD_NVL,'') PRAD_MEL_RTRN_CD_NVL from dbo.CMC_PRAD_ADDRESS" -o "C:\facets\CMC_PRAD_ADDRESS.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PRPR_ID,'') PRPR_ID, coalesce(NWNW_ID,'') NWNW_ID, coalesce(NWPR_PFX,'') NWPR_PFX, coalesce(NWPR_PCP_IND,'') NWPR_PCP_IND, coalesce(NWPR_EFF_DT,'') NWPR_EFF_DT, coalesce(NWPR_TERM_DT,'') NWPR_TERM_DT, coalesce(NWPR_MCTR_TRSN,'') NWPR_MCTR_TRSN, coalesce(AGAG_ID,'') AGAG_ID, coalesce(NWPR_MAX_PATIENT,'') NWPR_MAX_PATIENT, coalesce(NWPR_MIN_AGE,'') NWPR_MIN_AGE, coalesce(NWPR_MAX_AGE,'') NWPR_MAX_AGE, coalesce(NWPR_SEX,'') NWPR_SEX, coalesce(NWPR_ACC_PAT_IND,'') NWPR_ACC_PAT_IND, coalesce(NWPR_ACC_MEDCR_IND,'') NWPR_ACC_MEDCR_IND, coalesce(NWPR_ACC_MEDCD_IND,'') NWPR_ACC_MEDCD_IND, coalesce(NWPR_DIRECTORY_IND,'') NWPR_DIRECTORY_IND, coalesce(NWPR_PROV_DIR_IND,'') NWPR_PROV_DIR_IND, coalesce(NWPR_PAY_HOLD_DT,'') NWPR_PAY_HOLD_DT, coalesce(NWPR_RWH_OVR_PCT,'') NWPR_RWH_OVR_PCT, coalesce(NWPR_OPTS,'') NWPR_OPTS, coalesce(NWPR_RWH_IND,'') NWPR_RWH_IND, coalesce(NWPR_PAT_CTR,'') NWPR_PAT_CTR, coalesce(NWPR_MCTR_RSTR,'') NWPR_MCTR_RSTR, coalesce(NWPR_PAT_CTR_DTM,'') NWPR_PAT_CTR_DTM, coalesce(NWPR_AUTO_PCP_IND,'') NWPR_AUTO_PCP_IND, coalesce(SVAR_ID,'') SVAR_ID, coalesce(NWPR_CAP_RET_CD,'') NWPR_CAP_RET_CD, coalesce(NWPR_CAP_RET_MOS,'') NWPR_CAP_RET_MOS, coalesce(NWPR_LOCK_TOKEN,'') NWPR_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID, coalesce(SYS_LAST_UPD_DTM,'') SYS_LAST_UPD_DTM, coalesce(SYS_USUS_ID,'') SYS_USUS_ID, coalesce(SYS_DBUSER_ID,'') SYS_DBUSER_ID from dbo.CMC_NWPR_RELATION" -o "C:\facets\CMC_NWPR_RELATION.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(PDBC_PFX,'') PDBC_PFX, coalesce(PRPR_ID,'') PRPR_ID, coalesce(NPPR_EFF_DT,'') NPPR_EFF_DT, coalesce(NPPR_TERM_DT,'') NPPR_TERM_DT, coalesce(AGAG_ID,'') AGAG_ID, coalesce(NPPR_OPTS,'') NPPR_OPTS, coalesce(NPPR_MCTR_TRSN,'') NPPR_MCTR_TRSN, coalesce(NPPR_LOCK_TOKEN,'') NPPR_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID from dbo.CMC_NPPR_AGGR" -o "C:\facets\CMC_NPPR_AGGR.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(NWNW_ID,'') NWNW_ID, coalesce(MCAR_AREA_ID,'') MCAR_AREA_ID, coalesce(NWNW_NAME,'') NWNW_NAME, coalesce(NWNW_ADDR1,'') NWNW_ADDR1, coalesce(NWNW_ADDR2,'') NWNW_ADDR2, coalesce(NWNW_ADDR3,'') NWNW_ADDR3, coalesce(NWNW_CITY,'') NWNW_CITY, coalesce(NWNW_STATE,'') NWNW_STATE, coalesce(NWNW_ZIP,'') NWNW_ZIP, coalesce(NWNW_COUNTY,'') NWNW_COUNTY, coalesce(NWNW_CTRY_CD,'') NWNW_CTRY_CD, coalesce(NWNW_PHONE,'') NWNW_PHONE, coalesce(NWNW_PHONE_EXT,'') NWNW_PHONE_EXT, coalesce(NWNW_FAX,'') NWNW_FAX, coalesce(NWNW_FAX_EXT,'') NWNW_FAX_EXT, coalesce(NWNW_EMAIL,'') NWNW_EMAIL, coalesce(NWNW_MCTR_TYPE,'') NWNW_MCTR_TYPE, coalesce(NWNW_NAME_XLOW,'') NWNW_NAME_XLOW, coalesce(NWNW_CITY_XLOW,'') NWNW_CITY_XLOW, coalesce(NWNW_LOCK_TOKEN,'') NWNW_LOCK_TOKEN, coalesce(ATXR_SOURCE_ID,'') ATXR_SOURCE_ID from dbo.CMC_NWNW_NETWORK" -o "C:\facets\CMC_NWNW_NETWORK.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; with change as (select PRPR_ID, COUNT(distinct PRCF_MCTR_SPEC) as cnt from audit.CMC_PRPR_PROV where len(PRPR_ID) = 8 group by PRPR_ID having COUNT(distinct PRCF_MCTR_SPEC) > 1 union select PRPR_ID, COUNT(distinct TPCT_MCTR_TCAT) as cnt from audit.CMC_PRPR_PROV where len(PRPR_ID) = 8 group by PRPR_ID having COUNT(distinct TPCT_MCTR_TCAT) > 1) select distinct a.PRPR_ID, CONVERT(date, a.HIST_CREATE_DTM) as HIST_CREATE_DATE, PRCF_MCTR_SPEC, TPCT_MCTR_TCAT from audit.CMC_PRPR_PROV a join change c on a.PRPR_ID = c.PRPR_ID " -o "C:\facets\change.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select coalesce(CLCL_ID,'') as CLCL_ID, coalesce(PRPR_ID,'') as PRPR_ID, coalesce(cast(CLCL_LOW_SVC_DT AS DATE),'') as CLCL_LOW_SVC_DT, coalesce(CAST(CLCL_HIGH_SVC_DT AS DATE),'') as CLCL_HIGH_SVC_DT , coalesce(cast(CLCL_PAID_DT AS DATE),'') as CLCL_PAID_DT, coalesce(CLCL_CUR_STS,'') as CLCL_CUR_STS, coalesce(NWPR_PFX,'') as NWPR_PFX, coalesce(NWNW_ID,'') as NWNW_ID, coalesce(AGAG_ID,'') as AGAG_ID, coalesce(PDPD_ID,'') as PDPD_ID, coalesce(CLCL_TOT_CHG,'') as CLCL_TOT_CHG, coalesce(CLCL_TOT_PAYABLE,'') as CLCL_TOT_PAYABLE from dbo.CMC_CLCL_CLAIM" -o "C:\facets\CMC_CLCL_CLAIM.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; select * from dbo.CMC_PDDS_PROD_DESC " -o "C:\facets\CMC_PDDS_PROD_DESC.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0 -s "|" -W -Q "set nocount on; SELECT coalesce(AGAG_ID,'') as AGAG_ID,coalesce(AGAG_EFF_DT,'') as AGAG_EFF_DT,coalesce(AGAG_TERM_DT,'') as AGAG_TERM_DT,coalesce(AGAG_CAT,'') as AGAG_CAT,coalesce(AGAG_MCTR_TYPE,'') as AGAG_MCTR_TYPE,coalesce(AGAG_RWH_PCT,'') as AGAG_RWH_PCT,coalesce(AGAG_RWH_IND,'') as AGAG_RWH_IND,coalesce(AGAG_CL_ACPT_MNTHS,'') as AGAG_CL_ACPT_MNTHS,coalesce(AGAG_IP_PRICE_IND,'') as AGAG_IP_PRICE_IND,coalesce(AGAG_OP_PRICE_IND,'') as AGAG_OP_PRICE_IND,coalesce(AGAG_OP_MULT_PCT,'') as AGAG_OP_MULT_PCT,coalesce(AGAG_OL_IND,'') as AGAG_OL_IND,coalesce(AGAG_OL_DISC_PCT,'') as AGAG_OL_DISC_PCT,coalesce(AGAG_OL_LMT,'') as AGAG_OL_LMT,coalesce(AGAG_OL_EXCD_ID,'') as AGAG_OL_EXCD_ID,coalesce(AGAG_MIN_DISC_PCT,'') as AGAG_MIN_DISC_PCT,coalesce(AGAG_MAX_DISC_PCT,'') as AGAG_MAX_DISC_PCT,coalesce(AGAG_MXD_EXCD_ID,'') as AGAG_MXD_EXCD_ID,coalesce(AGAG_ST_DISC_PCT,'') as AGAG_ST_DISC_PCT,coalesce(AGAG_ST_DISC_IND,'') as AGAG_ST_DISC_IND,coalesce(AGAG_ST_DISC_PRC,'') as AGAG_ST_DISC_PRC,coalesce(AGAG_STD_EXCD_ID,'') as AGAG_STD_EXCD_ID,coalesce(AGAG_SUP_DISC_PCT,'') as AGAG_SUP_DISC_PCT,coalesce(AGAG_SUP_DISC_EXCD,'') as AGAG_SUP_DISC_EXCD,coalesce(AGAG_DRAG_FROM_IND,'') as AGAG_DRAG_FROM_IND,coalesce(AGAG_DRAG_PER_IND,'') as AGAG_DRAG_PER_IND,coalesce(AGAG_DRAG_PERIOD,'') as AGAG_DRAG_PERIOD,coalesce(AGAG_DRAG_PERIOD2,'') as AGAG_DRAG_PERIOD2,coalesce(AGAG_DRAG_PERIOD3,'') as AGAG_DRAG_PERIOD3,coalesce(AGAG_DRAG_EOB_IND,'') as AGAG_DRAG_EOB_IND,coalesce(AGSE_PFX,'') as AGSE_PFX,coalesce(AGAG_ACPLUS_IND,'') as AGAG_ACPLUS_IND, coalesce(AGAG_ID_XLOW,'') as AGAG_ID_XLOW,coalesce(AGAG_DELG_CLAIMS,'') as AGAG_DELG_CLAIMS,coalesce(AGAG_DELG_UM,'') as AGAG_DELG_UM,coalesce(AGAG_DELG_CASE,'') as AGAG_DELG_CASE,coalesce(AGAG_NWX_PROF_IND,'') as AGAG_NWX_PROF_IND,coalesce(AGAG_DESC,'') as AGAG_DESC FROM dbo.CMC_AGAG_AGREEMENT;" -o "C:\facets\CMC_AGAG_AGREEMENT.txt" 
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0custom -s "|" -W -Q "set nocount on; select * from dbo.tpzt_apm_1220_RelatedEntities_Hold " -o "C:\facets\tpzt_apm_1220_RelatedEntities_Hold.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0custom -s "|" -W -Q "set nocount on; select * from dbo.tpzt_apm_0070_Channeling_Hold " -o "C:\facets\tpzt_apm_0070_Channeling_Hold.txt"
sqlcmd -S 205.170.139.226,11004 -U ***** -P ***** -d fabncpr0custom -s "|" -W -Q "set nocount on; select * from dbo.tpzt_apm_0010_Demographics_Hold " -o "C:\facets\tpzt_apm_0010_Demographics_Hold.txt"

:: copy files to shared drive
copy "C:\facets\tpzt_apm_fac_xwlk.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\tpzt_apm_fac_xwlk.txt"
copy "C:\facets\CMC_MCBR_BANK_REL.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\CMC_MCBR_BANK_REL.txt"
copy "C:\facets\CMC_MCTI_TAX_INFO.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\CMC_MCTI_TAX_INFO.txt"
copy "C:\facets\ACCT_REMIT.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\ACCT_REMIT.txt"
copy "C:\facets\CMC_PRDS_DATE.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\CMC_PRDS_DATE.txt"
copy "C:\facets\CMC_MCTN_TAX_NAME.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\CMC_MCTN_TAX_NAME.txt"
copy "C:\facets\CMC_MCTR_CD_TRANS.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\CMC_MCTR_CD_TRANS.txt"
copy "C:\facets\cmc_nwpr_relation.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_nwpr_relation.txt"
copy "C:\facets\cmc_prpr_prov.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_prpr_prov.txt"
copy "C:\facets\cmc_nppr_aggr.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_nppr_aggr.txt"
copy "C:\facets\cmc_prer_relation.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_prer_relation.txt"
copy "C:\facets\cmc_nwnw_network.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_nwnw_network.txt"
copy "C:\facets\cmc_prad_address.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_prad_address.txt"
copy "C:\facets\change.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\change.txt"
copy "C:\facets\CMC_AGAG_AGREEMENT.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_agag_agreement.txt"
copy "C:\facets\cmc_clcl_claim.txt"  "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\cmc_clcl_claim.txt"
copy "C:\facets\tpzt_apm_1220_RelatedEntities_Hold.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\tpzt_apm_1220_RelatedEntities_Hold.txt"
copy "C:\facets\tpzt_apm_0070_Channeling_Hold.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\tpzt_apm_0070_Channeling_Hold.txt"
copy "C:\facets\tpzt_apm_0010_Demographics_Hold.txt" "I:\Network Management Support\Development\Reports\Quality Audit Reports\SASsource\tpzt_apm_0010_Demographics_Hold.txt"

:: call sas batch program.  pull facets data.. create datasets.. run queries
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -CONFIG "C:\Program Files\SASHome\SASFoundation\9.4\nls\en\sasv9.cfg" -AUTOEXEC "H:\AUTOEXEC.SAS" -SYSIN "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F-QueryDailyFullBatch.sas" -LOG  "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F-QueryDailyFullBatch.log" -PRINT "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F-QueryDailyFullBatch.lst"

:: create historical log file
copy "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\SAS Programs\F-QueryDailyFullBatch.log" "I:\Network Management Support\Development\Quality Audit Reporting\Facets Extracts\Data Build Logs\%date:/=_%_F-QueryDailyFullBatch.log"

:: call fbatchy
call "I:\Network Management Support\Development\Quality Audit Reporting\Audit Queries\Query Batcher\Fbatchy.bat"
